ALTER TABLE plans ADD COLUMN title TEXT;
ALTER TABLE plans ADD COLUMN what TEXT;
ALTER TABLE plans ADD COLUMN why TEXT;
ALTER TABLE plans ADD COLUMN ends TEXT;
ALTER TABLE verdicts ADD COLUMN message TEXT;
